export const enum Dia {
  DILLUNS = 'DILLUNS',
  DIMARTS = 'DIMARTS',
  DIMECRES = 'DIMECRES',
  DIJOUS = 'DIJOUS',
  DIVENDRES = 'DIVENDRES',
  DISSABTE = 'DISSABTE',
  DIUMENGE = 'DIUMENGE',
  QUALSEVOL = 'QUALSEVOL'
}
